flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    image = FileField('Attach image to your post',
                      validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Post')

flaskblog/comments/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Comment
from flaskblog.comments.forms import UpdateCommentForm

comments = Blueprint('comments', __name__)


@comments.route('/comment/<int:comment_id>', methods=['GET', 'POST'])
@login_required
def update_delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.author != current_user:
        abort(403)
    form = UpdateCommentForm()

    if form.validate_on_submit():
        if form.update.data:
            comment.content = form.content.data
            db.session.commit()
            flash('Your comment has been updated', 'success')
            return redirect(url_for('posts.post', post_id=comment.post_id))
        elif form.delete.data:
            db.session.delete(comment)
            db.session.commit()
            flash('Your comment has been deleted!', 'success')
            return redirect(url_for('posts.post', post_id=comment.post_id))
    elif request.method == 'GET':
        form.content.data = comment.content

    return render_template("comments/comment.html", comment=comment, form=form)

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Comment, PostLike
from flaskblog.posts.forms import PostForm
from flaskblog.comments.forms import CommentForm
from flaskblog.users.utils import save_picture, remove_picture

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.image.data:
            post_image = save_picture(form.image.data,
                                      directory='static/post_image')
            post = Post(title=form.title.data, content=form.content.data,
                        author=current_user, image_file=post_image)
        else:
            post = Post(title=form.title.data, content=form.content.data,
                        author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template("posts/create_post.html", title="New Post",
                           form=form, legend="New Post")


@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            comment = Comment(content=form.content.data,
                              author_id=current_user.id, post_id=post.id)
            db.session.add(comment)
            db.session.commit()
            flash('Your comment has been published!', 'success')
            return redirect(url_for('posts.post', post_id=post.id))
        else:
            flash('You need to login to write comments!', 'danger')

    comments_of_post = Comment.query.filter_by(post_id=post.id). \
        order_by(Comment.date_commented.desc()).all()

    return render_template("posts/post.html", title=post.title, post=post,
                           form=form, comments=comments_of_post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()

    if form.validate_on_submit():
        if form.image.data:
            post_image = save_picture(form.image.data,
                                      directory='static/post_image')
            # if post already has image, remove it
            if post.image_file:
                old_image = post.image_file
                remove_picture(old_image, directory='static/post_image')
            post.image_file = post_image

        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template("posts/create_post.html", title="Update Post",
                           form=form, legend="Update Post")


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    # before deleting the post, delete its comments
    Comment.query.filter_by(post_id=post.id).delete()

    # before deleting the post, delete its likes
    PostLike.query.filter_by(post_id=post.id).delete()

    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(request.referrer)

flaskblog/users/routes.py
from flask import (render_template, url_for, flash, redirect, request,
                   session, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm,
                                   UpdateAccountForm, RequestResetForm,
                                   ResetPasswordForm, MobilePhoneEntryForm,
                                   ConfirmMobilePhoneForm)
from flaskblog.users.utils import (save_picture, remove_picture,
                                   send_reset_email, send_activation_email)
from flaskblog.users.messente_messaging import send_sms_pin

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        if send_activation_email(user):
            flash('Your account has been created! Account activation link '
                  'is sent to your email', 'success')
            return redirect(url_for('users.login'))
        else:
            flash("We were not able to deliver email to you. Try again.",
                  'danger')
            db.session.delete(user)
            db.session.commit()
            return redirect(url_for('users.register'))
    return render_template("users/register.html", title="Register", form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data) \
                and user.is_activated:
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else \
                redirect(url_for('main.home'))
        elif user and bcrypt.check_password_hash(user.password,
                                                 form.password.data) \
                and not user.is_activated:
            send_activation_email(user)
            flash(
                'You need to activate your account to login. Activation link '
                'has been sent to your email', 'danger')
        else:
            flash('Login Unsuccessful. Please check email and password',
                  'danger')
    return render_template("users/login.html", title="Login", form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            if current_user.image_file != "default.jpg":
                old_picture = current_user.image_file
                remove_picture(old_picture)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' +
                                            current_user.image_file)
    return render_template("users/account.html", title="Account",
                           image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template("posts/user_posts.html", posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if send_reset_email(user):
            flash(
                'An email has been sent with instructions to reset your password.',
                'info')
            return redirect(url_for('users.login'))
        else:
            flash(
                'We could not deliver email with reset instructions to you.'
                ' Try again later.',
                'danger')
            return redirect(url_for('users.reset_request'))
    return render_template("users/reset_request.html", title="Reset Password",
                           form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in',
              'success')
        return redirect(url_for('users.login'))
    return render_template("users/reset_token.html", title="Reset Password",
                           form=form)


@users.route('/activate_account/<token>', methods=['GET', 'POST'])
def activate_account(token):
    user = User.verify_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.login'))
    elif user:
        user.is_activated = True
        db.session.commit()
        flash('Your account has been activated. You can now login.', 'success')
        return redirect(url_for('users.login'))


@users.route('/link_mobile_phone', methods=['GET', 'POST'])
@login_required
def link_mobile_phone():
    form = MobilePhoneEntryForm()
    if form.validate_on_submit():
        full_number = form.country_code.data + form.phone_number.data
        pin_code = send_sms_pin(full_number)
        if pin_code:
            session['pin_code'] = pin_code
            session['phone_number'] = full_number
            flash('We have sent PIN code to your number', 'success')
            return redirect(url_for('users.confirm_mobile_phone'))
        else:
            flash(
                'We were not able to deliver sms to you. Please try '
                'again later.', 'danger')
    return render_template("users/link_mobile_number.html", form=form)


@users.route('/confirm_mobile_phone', methods=['GET', 'POST'])
@login_required
def confirm_mobile_phone():
    form = ConfirmMobilePhoneForm()
    pin_code = session.get('pin_code', None)
    phone_number = session.get('phone_number', None)
    if pin_code and phone_number and form.validate_on_submit():
        if pin_code == int(form.pin_code.data):
            current_user.mobile_phone = phone_number
            db.session.commit()
            flash('Your mobile phone number is confirmed', 'success')
            return redirect(url_for('users.account'))
        else:
            flash('You entered incorrect PIN, try again.', 'danger')
            return redirect(url_for('users.link_mobile_phone'))
    return render_template("users/confirm_mobile_phone.html", form=form)


@users.route('/like/<int:post_id>/<action>')
@login_required
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
        flash('You liked the post!', 'alert alert-primary')
    elif action == 'dislike':
        current_user.unlike_post(post)
        db.session.commit()
        flash('You disliked the post!', 'alert alert-warning')
    return redirect(url_for("posts.post", post_id=post_id))

flaskblog/templates/posts/create_post.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}

                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}

                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.image.label() }}
                    {{ form.image(class="form-control-file") }}
                    {% if form.image.errors %}
                        {% for error in form.image.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/posts/post.html
{% extends "layout.html" %}

{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2"
                   href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                    <div cl>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                           href="{{ url_for('posts.update_post', post_id = post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1"
                                data-toggle="modal" data-target="#deleteModal">
                            Delete
                        </button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
            {% if post.image_file %}
                <img src="{{ url_for('static', filename='post_image/' + post.image_file) }}"
                     class="img-fluid" alt="Responsive image">
            {% else %}

            {% endif %}
            {% if post.number_of_likes() %}
                <p><em>This post has been liked <b>{{ post.number_of_likes() }}</b> times.</em></p>
            {% else %}
                <p><em>This post has not been liked yet. Like it!</em></p>
            {% endif %}
            <div class="float-right">
                {% if current_user.is_authenticated %}
                    {% if current_user.has_liked_post(post) %}
                        <a href=" {{ url_for('users.like_action', post_id = post.id, action = 'dislike') }} "><img
                                src="{{ url_for('static', filename='icons/dislike.svg') }}">
                        </a>
                    {% else %}
                        <a href=" {{ url_for('users.like_action', post_id = post.id, action = 'like') }} "><img
                                src="{{ url_for('static', filename='icons/like.svg') }}">
                        </a>
                    {% endif %}
                {% else %}

                {% endif %}
            </div>
        </div>
    </article>

    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.content.label("Enter your comment here: ") }}

                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>

    {% if comments %}
        <h5>Comments to the post: </h5>
        {% for comment in comments %}
            <article class="media content-section">
                <img class="rounded-circle article-img"
                     src="{{ url_for('static', filename='profile_pics/' + comment.author.image_file) }}">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="mr-2"
                           href="{{ url_for('users.user_posts', username=comment.author.username) }}">{{ comment.author.username }}</a>
                        says on:
                        <small class="text-muted">{{ comment.date_commented.strftime('%Y-%m-%d') }}</small>

                        {% if current_user == comment.author %}
                            <a href=" {{ url_for('comments.update_delete_comment', comment_id=comment.id) }} ">Edit
                                comment</a>
                        {% else %}

                        {% endif %}

                    </div>
                    <p class="article-content">{{ comment.content }}</p>
                </div>
            </article>
        {% endfor %}
    {% else %}
        <h5>This post has no comments! Comment it;-)</h5>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
         aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete
                        Post?</h5>
                    <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary"
                            data-dismiss="modal">Close
                    </button>
                    <form action="{{ url_for('posts.delete_post', post_id = post.id) }}"
                          method="POST">
                        <input class="btn btn-danger" type="submit"
                               value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

flaskblog/templates/posts/user_posts.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img"
                 src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2"
                       href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title"
                       href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a>
                </h2>
                <p class="article-content">{{ post.content }}</p>
                {% if post.image_file %}
                    <img src="{{ url_for('static', filename='post_image/' + post.image_file) }}"
                         class="img-fluid" alt="Responsive image">
                {% else %}

                {% endif %}
                {% if post.number_of_likes() %}
                    <p><em>This post has been liked
                        <b>{{ post.number_of_likes() }}</b> times.</em></p>
                {% else %}
                    <p><em>This post has not been liked yet. Like it!</em></p>
                {% endif %}
                <div class="float-right">
                    {% if current_user.is_authenticated %}
                        {% if current_user.has_liked_post(post) %}
                            <a href=" {{ url_for('users.like_action', post_id = post.id, action = 'dislike') }} "><img
                                    src="{{ url_for('static', filename='icons/dislike.svg') }}">
                            </a>
                        {% else %}
                            <a href=" {{ url_for('users.like_action', post_id = post.id, action = 'like') }} "><img
                                    src="{{ url_for('static', filename='icons/like.svg') }}">
                            </a>
                        {% endif %}
                    {% else %}
                    {% endif %}
                </div>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4"
                   href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}