flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,
                                                                  per_page=5)
    return render_template("main/home.html", posts=posts)


@main.route('/about')
def about():
    return render_template("main/about.html", title="About")


@main.route('/article/working_with_remote_server')
def working_with_remote_server():
    return render_template("main/articles/working_with_remote_server.html",
                           title="Working_with_remote_server")

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Comment, PostLike
from flaskblog.posts.forms import PostForm
from flaskblog.comments.forms import CommentForm
from flaskblog.users.utils import save_picture, remove_picture

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.image.data:
            post_image = save_picture(form.image.data,
                                      directory='static/post_image')
            post = Post(title=form.title.data, content=form.content.data,
                        author=current_user, image_file=post_image)
        else:
            post = Post(title=form.title.data, content=form.content.data,
                        author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template("posts/create_post.html", title="New Post",
                           form=form, legend="New Post")


@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            comment = Comment(content=form.content.data,
                              author_id=current_user.id, post_id=post.id)
            db.session.add(comment)
            db.session.commit()
            flash('Your comment has been published!', 'success')
            return redirect(url_for('posts.post', post_id=post.id))
        else:
            flash('You need to login to write comments!', 'danger')

    comments_of_post = Comment.query.filter_by(post_id=post.id). \
        order_by(Comment.date_commented.desc()).all()

    return render_template("posts/post.html", title=post.title, post=post,
                           form=form, comments=comments_of_post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()

    if form.validate_on_submit():
        if form.image.data:
            post_image = save_picture(form.image.data,
                                      directory='static/post_image')
            # if post already has image, remove it
            if post.image_file:
                old_image = post.image_file
                remove_picture(old_image, directory='static/post_image')
            post.image_file = post_image

        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    return render_template("posts/create_post.html", title="Update Post",
                           form=form, legend="Update Post")


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    # before deleting the post, delete its comments
    Comment.query.filter_by(post_id=post.id).delete()

    # before deleting the post, delete its likes
    PostLike.query.filter_by(post_id=post.id).delete()

    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(request.referrer)

flaskblog/users/routes.py
from flask import (render_template, url_for, flash, redirect, request,
                   session, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm,
                                   UpdateAccountForm, RequestResetForm,
                                   ResetPasswordForm, MobilePhoneEntryForm,
                                   ConfirmMobilePhoneForm)
from flaskblog.users.utils import (save_picture, remove_picture,
                                   send_reset_email, send_activation_email)
from flaskblog.users.messente_messaging import send_sms_pin

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        if send_activation_email(user):
            flash('Your account has been created! Account activation link '
                  'is sent to your email', 'success')
            return redirect(url_for('users.login'))
        else:
            flash("We were not able to deliver email to you. Try again.",
                  'danger')
            db.session.delete(user)
            db.session.commit()
            return redirect(url_for('users.register'))
    return render_template("users/register.html", title="Register", form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data) \
                and user.is_activated:
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else \
                redirect(url_for('main.home'))
        elif user and bcrypt.check_password_hash(user.password,
                                                 form.password.data) \
                and not user.is_activated:
            send_activation_email(user)
            flash(
                'You need to activate your account to login. Activation link '
                'has been sent to your email', 'danger')
        else:
            flash('Login Unsuccessful. Please check email and password',
                  'danger')
    return render_template("users/login.html", title="Login", form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            if current_user.image_file != "default.jpg":
                old_picture = current_user.image_file
                remove_picture(old_picture)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' +
                                            current_user.image_file)
    return render_template("users/account.html", title="Account",
                           image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template("posts/user_posts.html", posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if send_reset_email(user):
            flash(
                'An email has been sent with instructions to reset your password.',
                'info')
            return redirect(url_for('users.login'))
        else:
            flash(
                'We could not deliver email with reset instructions to you.'
                ' Try again later.',
                'danger')
            return redirect(url_for('users.reset_request'))
    return render_template("users/reset_request.html", title="Reset Password",
                           form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in',
              'success')
        return redirect(url_for('users.login'))
    return render_template("users/reset_token.html", title="Reset Password",
                           form=form)


@users.route('/activate_account/<token>', methods=['GET', 'POST'])
def activate_account(token):
    user = User.verify_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.login'))
    elif user:
        user.is_activated = True
        db.session.commit()
        flash('Your account has been activated. You can now login.', 'success')
        return redirect(url_for('users.login'))


@users.route('/link_mobile_phone', methods=['GET', 'POST'])
@login_required
def link_mobile_phone():
    form = MobilePhoneEntryForm()
    if form.validate_on_submit():
        full_number = form.country_code.data + form.phone_number.data
        pin_code = send_sms_pin(full_number)
        if pin_code:
            session['pin_code'] = pin_code
            session['phone_number'] = full_number
            flash('We have sent PIN code to your number', 'success')
            return redirect(url_for('users.confirm_mobile_phone'))
        else:
            flash(
                'We were not able to deliver sms to you. Please try '
                'again later.', 'danger')
    return render_template("users/link_mobile_number.html", form=form)


@users.route('/confirm_mobile_phone', methods=['GET', 'POST'])
@login_required
def confirm_mobile_phone():
    form = ConfirmMobilePhoneForm()
    pin_code = session.get('pin_code', None)
    phone_number = session.get('phone_number', None)
    if pin_code and phone_number and form.validate_on_submit():
        if pin_code == int(form.pin_code.data):
            current_user.mobile_phone = phone_number
            db.session.commit()
            flash('Your mobile phone number is confirmed', 'success')
            return redirect(url_for('users.account'))
        else:
            flash('You entered incorrect PIN, try again.', 'danger')
            return redirect(url_for('users.link_mobile_phone'))
    return render_template("users/confirm_mobile_phone.html", form=form)


@users.route('/like/<int:post_id>/<action>')
@login_required
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
        flash('You liked the post!', 'alert alert-primary')
    elif action == 'dislike':
        current_user.unlike_post(post)
        db.session.commit()
        flash('You disliked the post!', 'alert alert-warning')
    return redirect(url_for("posts.post", post_id=post_id))

flaskblog/templates/home.html
{% extends "layout.html" %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
                {% if post.number_of_likes() %}
                    <p><em>This post has been liked <b>{{ post.number_of_likes() }}</b> times.</em></p>
                {% else %}
                    <p><em>This post has not been liked yet. Like it!</em></p>
                {% endif %}
                <div class="float-right">
                    {% if current_user.has_liked_post(post) %}
                        <a href=" {{ url_for('users.like_action', post_id = post.id, action = 'dislike') }} "><img src="{{ url_for('static', filename='icons/dislike.svg') }}">
                        </a>
                    {% else %}
                        <a href=" {{ url_for('users.like_action', post_id = post.id, action = 'like') }} "><img src="{{ url_for('static', filename='icons/like.svg') }}">
                        </a>
                    {% endif %}
                </div>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
          crossorigin="anonymous">

    <link rel="stylesheet" type="text/css"
          href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarToggle" aria-controls="navbarToggle"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link"
                       href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link"
                       href="{{ url_for('main.about') }}">About</a>
                    <a class="nav-item nav-link"
                       href="{{ url_for('static', filename='mycv.pdf') }}">My CV</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <h3>Welcome back, {{ current_user.username }}!</h3>
                        <a class="nav-item nav-link"
                           href="{{ url_for('posts.new_post') }}">Create
                            Post</a>
                        <a class="nav-item nav-link"
                           href="{{ url_for('users.account') }}">My Account</a>
                        <a class="nav-item nav-link"
                           href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link"
                           href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link"
                           href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Development</h3>
                <p class='text-muted'>Here are some of my articles about
                    development
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light"><a
                            href="{{ url_for('main.working_with_remote_server') }}">Working
                        with remote server using git</a>
                    </li>
                    <li class="list-group-item list-group-item-light">Setting
                        up local development environment
                    </li>
                    <li class="list-group-item list-group-item-light">Gunicorn
                        and Nginx on DigitalOcean VPS
                    </li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
            </div>
        </div>
    </div>

    <svg class="bi bi-laptop" width="1em" height="1em" viewBox="0 0 16 16"
         fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
              d="M13.5 3h-11a.5.5 0 0 0-.5.5V11h12V3.5a.5.5 0 0 0-.5-.5zm-11-1A1.5 1.5 0 0 0 1 3.5V12h14V3.5A1.5 1.5 0 0 0 13.5 2h-11z"/>
        <path d="M0 12h16v.5a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 12.5V12z"/>
    </svg>

</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
                {% if post.number_of_likes() %}
                    <p><em>This post has been liked <b>{{ post.number_of_likes() }}</b> times.</em></p>
                {% else %}
                    <p><em>This post has not been liked yet. Like it!</em></p>
                {% endif %}
                <div class="float-right">
                    {% if current_user.has_liked_post(post) %}
                        <a href=" {{ url_for('users.like_action', post_id = post.id, action = 'dislike') }} "><img src="{{ url_for('static', filename='icons/dislike.svg') }}">
                        </a>
                    {% else %}
                        <a href=" {{ url_for('users.like_action', post_id = post.id, action = 'like') }} "><img src="{{ url_for('static', filename='icons/like.svg') }}">
                        </a>
                    {% endif %}
                </div>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}